# Generated by Django 5.0.6 on 2025-09-22 05:12

import secrets

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


def generate_app_ids(apps, schema_editor):
    Assignment = apps.get_model("api", "Assignment")
    existing_ids = set(
        Assignment.objects.exclude(app_id__isnull=True).values_list("app_id", flat=True)
    )

    def _next_id() -> str:
        while True:
            candidate = secrets.token_hex(4).upper()
            if candidate not in existing_ids:
                existing_ids.add(candidate)
                return candidate

    for assignment in Assignment.objects.filter(app_id__isnull=True):
        assignment.app_id = _next_id()
        if not assignment.description:
            assignment.description = "NA"
        assignment.save(update_fields=["app_id", "description", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_project_to_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="app_id",
            field=models.CharField(
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{8}$", "Must be 8 alphanumeric characters"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.TextField(
                blank=True,
                default="NA",
                help_text="Auto-generated description from LLM analysis of memories",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(generate_app_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assignment",
            name="app_id",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{8}$", "Must be 8 alphanumeric characters"
                    )
                ],
            ),
        ),
    ]
