version: '3.9'
services:
  web:
    build: ./backend
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mastermind.settings
      - MEM0_API_KEY=${MEM0_API_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mastermind
      POSTGRES_USER: mastermind
      POSTGRES_PASSWORD: mastermind
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastermind"]
      interval: 10s
      timeout: 5s
      retries: 5
